export interface Wallpaper {
  id: string
  date: string
  imageUrl: string
  thumbnailUrl?: string
  title: string
  description?: string
  story?: string // 壁纸背后的故事/原因
  photographer?: string
  source?: string
}


export const wallpapers: Wallpaper[] = [
  {
    id: '1',
    date: '2026-02-06',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1080&q=95',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80',
    title: 'Mountain Peak',
    description: 'Majestic alpine summit bathed in golden light',
    story: 'On this day in 1971, Apollo 14 astronauts returned from the moon. This mountain peak reminds us of humanity\'s eternal drive to reach new heights and explore the unknown.',
    photographer: 'John Doe',
    source: 'Unsplash',
  },
  {
    id: '2',
    date: '2026-02-07',
    imageUrl: 'https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=1080&q=95',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=600&q=80',
    title: 'Ocean Waves',
    description: 'Serene coastal landscape at dusk',
    story: 'Charles Dickens was born on this day in 1812. Like the endless rhythm of ocean waves, his timeless stories continue to resonate through generations.',
    photographer: 'Jane Smith',
    source: 'Unsplash',
  },
  {
    id: '3',
    date: '2026-02-08',
    imageUrl: 'https://images.unsplash.com/photo-1465146633011-14f8e0781093?w=1080&q=95',
    thumbnailUrl: 'https://images.unsplash.com/photo-1465146633011-14f8e0781093?w=600&q=80',
    title: 'Wildflower Meadow',
    description: 'Vibrant spring blooms in morning light',
    story: 'Today marks the traditional beginning of spring in many cultures. These wildflowers symbolize renewal, hope, and the promise of warmer days ahead.',
    photographer: 'Alice Johnson',
    source: 'Unsplash',
  },
  {
    id: '4',
    date: '2026-02-09',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1080&q=95',
    thumbnailUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80',
    title: 'Forest Path',
    description: 'Enchanting woodland trail through ancient trees',
    story: 'On this day in 1964, The Beatles made their first appearance on The Ed Sullivan Show. This forest path invites us to take the road less traveled, just as they revolutionized music.',
    photographer: 'Bob Williams',
    source: 'Unsplash',
  },
  {
    id: '5',
    date: '2026-02-10',
    imageUrl: 'https://images.unsplash.com/photo-1758794093166-271d03ffd941?w=1080&q=95',
    thumbnailUrl: 'https://images.unsplash.com/photo-1758794093166-271d03ffd941?w=600&q=80',
    title: 'Perito Moreno Glacier',
    description: 'Massive blue glacier with turquoise meltwater and floating icebergs',
    story: 'On this day in 1985, China\'s Great Wall Station was completed in Antarctica, marking the beginning of Chinese polar exploration. Like this ancient glacier standing through millennia, human curiosity for the unknown endures forever.',
    photographer: 'Grégory Andrey',
    source: 'Unsplash',
  },
  {
    id: '6',
    date: '2026-02-11',
    imageUrl: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=1080&q=95',
    thumbnailUrl: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=600&q=80',
    title: 'Light of Freedom',
    description: 'Warm sunlight breaking through dramatic clouds at dawn',
    story: 'On this day in 1990, Nelson Mandela walked free after 27 years. He chose forgiveness to light the future. Like this sunrise, after the deepest night, dawn always comes. Freedom is not a sudden gift, but a crack carved by countless people with persistence. Today, let this light remind us: hope never gives up.',
    photographer: 'Johannes Plenio',
    source: 'Unsplash',
  },
  {
    id: '7',
    date: '2026-02-12',
    imageUrl: 'https://images.unsplash.com/photo-1762430440987-fc9c3f7bd961?w=1080&q=95',
    thumbnailUrl: 'https://images.unsplash.com/photo-1762430440987-fc9c3f7bd961?w=600&q=80',
    title: 'Breaking Chains',
    description: 'Statue of two men breaking chains under a clear sky',
    story: 'On this day in 1809, Abraham Lincoln was born. Also on this exact day, Charles Darwin entered the world. One freed millions from slavery, the other liberated human thought from ignorance. Two men, same birthday, both changed history by breaking chains—one visible, one invisible. Today we celebrate the power of liberation.',
    photographer: 'Adeyemi Bamtefa',
    source: 'Unsplash',
  },
  {
    id: '8',
    date: '2026-02-13',
    imageUrl: 'https://images.unsplash.com/photo-1643083813177-8e0263e50ddb?w=1080&q=95',
    thumbnailUrl: 'https://images.unsplash.com/photo-1643083813177-8e0263e50ddb?w=600&q=80',
    title: 'Lucy in the Sky',
    description: 'Milky Way photographed vertically at night',
    story: 'On this day in 2004, astronomers announced the discovery of the largest diamond in the universe—a white dwarf star named "Lucy" after The Beatles\' song. This cosmic gem, 50 light-years away, is a crystallized carbon star 10 billion trillion trillion carats. Tonight, as you gaze at the stars, remember: the universe is not cold emptiness, but a treasury of wonders waiting to be found.',
    photographer: 'Gabriel Mihalcea',
    source: 'Unsplash',
  },
  {
    id: '9',
    date: '2026-02-14',
    imageUrl: 'https://images.unsplash.com/photo-1727879399908-7a8575cd5bc3?w=1080&q=95',
    thumbnailUrl: 'https://images.unsplash.com/photo-1727879399908-7a8575cd5bc3?w=600&q=80',
    title: 'The Importance of Being in Love',
    description: 'Silhouettes of a couple looking at each other at golden hour',
    story: 'On this day in 1895, Oscar Wilde\'s "The Importance of Being Earnest" premiered in London. That same night, love letters were exchanged, vows whispered, hearts broken and mended. Wilde once wrote: "To love oneself is the beginning of a lifelong romance." Today, as sunlight crowns two silhouettes, remember—love is the only serious thing worth being earnest about.',
    photographer: 'Pedro Pulido',
    source: 'Unsplash',
  },
  {
    id: '10',
    date: '2026-02-15',
    imageUrl: 'https://images.unsplash.com/photo-1756326518956-e9388bd205b4?w=1080&q=95',
    thumbnailUrl: 'https://images.unsplash.com/photo-1756326518956-e9388bd205b4?w=600&q=80',
    title: 'The Blue Danube',
    description: 'Hungarian Parliament Building illuminated at the blue hour, reflected in the Danube River',
    story: 'On this day in 1867, Johann Strauss II premiered "The Blue Danube" waltz in Vienna. It flopped at first—critics yawned, audiences shrugged. Yet today it\'s the world\'s most beloved waltz, played at midnight every New Year\'s Eve. Like this parliament standing proud over the Danube at dusk, some masterpieces need time to reveal their brilliance. The river flows on; the music plays forever.',
    photographer: 'Himmel S',
    source: 'Unsplash',
  },
  {
    id: '11',
    date: '2026-02-16',
    imageUrl: 'https://images.unsplash.com/photo-1648139210431-f5a62bc3f126?w=1080&q=95',
    thumbnailUrl: 'https://images.unsplash.com/photo-1648139210431-f5a62bc3f126?w=600&q=80',
    title: 'Wonderful Things',
    description: 'Golden corridor inside a pharaoh\'s tomb in the Valley of the Kings',
    story: 'On this day in 1923, Howard Carter unsealed the burial chamber of Tutankhamun and glimpsed "wonderful things"—gold glinting in candlelight, the face of a boy-king asleep for 3,300 years. This corridor echoes that moment: hieroglyphs whisper secrets, golden light beckons forward. Some discoveries don\'t just reveal the past—they redefine how we see ourselves.',
    photographer: 'Michael Starkie',
    source: 'Unsplash',
  },
]
